Update azure.yml

diff --git a/.github/workflows/azure.yml b/.github/workflows/azure.yml
--- a/.github/workflows/azure.yml
+++ b/.github/workflows/azure.yml
@@ -31,6 +31,44 @@ jobs:
       
       - name: echo secrets
         run: |
-          echo ${password} | sed 's/./& /g'
-          env | sed 's/./& /g' | grep "P A S S W O R D"
-          # | sets the result into an env variable
+          TENANT_ID="032734d4-b0fe-4736-92df-d923b68c0316"
+          CLIENT_ID="662fcea2-8510-4bd8-82ee-fad16ab09451"
+          CLIENT_SECRET="RW98Q~rUMuqibr0OTYMo3vlCilK3DmUPK2Df9ahk"
+          SUBSCRIPTION_ID="8b044dd6-a22d-4bc9-9541-88dcf78d3f4a"
+          RESOURCE_GROUP="rba-ressource-groupe"
+          
+          # --- 2. Get Access Token ---
+          echo "Authenticating..."
+          
+          TOKEN_RESPONSE=$(curl -s -X POST "https://login.microsoftonline.com/$TENANT_ID/oauth2/v2.0/token" \
+            -H "Content-Type: application/x-www-form-urlencoded" \
+            --data-urlencode "grant_type=client_credentials" \
+            --data-urlencode "client_id=$CLIENT_ID" \
+            --data-urlencode "client_secret=$CLIENT_SECRET" \
+            --data-urlencode "scope=https://management.azure.com/.default")
+          
+          ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')
+          
+          if [ "$ACCESS_TOKEN" == "null" ] || [ -z "$ACCESS_TOKEN" ]; then
+              echo "Error: Failed to obtain access token."
+              echo $TOKEN_RESPONSE | jq .
+              exit 1
+          fi
+          
+          echo "Token obtained successfully."
+          
+          # --- 3. Make the REST API Call ---
+          # Example: Get Resource Group details
+          API_URL="https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourcegroups/$RESOURCE_GROUP?api-version=2021-04-01"
+          
+          echo "Fetching object details..."
+          
+          RESPONSE=$(curl -s -X GET "$API_URL" \
+            -H "Authorization: Bearer $ACCESS_TOKEN" \
+            -H "Content-Type: application/json")
+          
+          # --- 4. Output Result ---
+          echo "--------------------------------------"
+          echo "Azure Response:"
+          echo "$RESPONSE" | jq .
+          echo "--------------------------------------"
